anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false
[toolchain]
anchor_version = "0.29.0"

[programs.devnet]
mooar = "92X4MQTZBVb1LHJhZmaMSRzqYWWqcZfrQnmvZCuRyNxV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/redeem-test.ts"
